module TestDataChecks02
    using Base.Test
    using CSVReaders

    path = joinpath("test", "data", "02_movies.csv")
    sizehint = filesize(path)

    reader = CSVReaders.CSVReader()
    io = open(path, "r")
    output = readall(Vector{Any}, io, reader, sizehint)
    close(io)

    M = transpose(reshape(output, 25, 58788))

    movies = Array(Any, 58788)

    movies[1] = Any[
        Nullable(1),
        Nullable("\$"),
        Nullable(1971),
        Nullable(121),
        Nullable{Int}(),
        Nullable(6.4),
        Nullable(348),
        Nullable(4.5),
        Nullable(4.5),
        Nullable(4.5),
        Nullable(4.5),
        Nullable(14.5),
        Nullable(24.5),
        Nullable(24.5),
        Nullable(14.5),
        Nullable(4.5),
        Nullable(4.5),
        Nullable(""),
        Nullable(0),
        Nullable(0),
        Nullable(1),
        Nullable(1),
        Nullable(0),
        Nullable(0),
        Nullable(0),
    ]

    movies[2] = Any[
        Nullable(2),
        Nullable("\$1000 a Touchdown"),
        Nullable(1939),
        Nullable(71),
        Nullable{Int}(),
        Nullable(6.0),
        Nullable(20),
        Nullable(0.0),
        Nullable(14.5),
        Nullable(4.5),
        Nullable(24.5),
        Nullable(14.5),
        Nullable(14.5),
        Nullable(14.5),
        Nullable(4.5),
        Nullable(4.5),
        Nullable(14.5),
        Nullable(""),
        Nullable(0),
        Nullable(0),
        Nullable(1),
        Nullable(0),
        Nullable(0),
        Nullable(0),
        Nullable(0),
    ]

    movies[3] = Any[
        Nullable(3),
        Nullable("\$21 a Day Once a Month"),
        Nullable(1941),
        Nullable(7),
        Nullable{Int}(),
        Nullable(8.2),
        Nullable(5),
        Nullable(0.0),
        Nullable(0.0),
        Nullable(0.0),
        Nullable(0.0),
        Nullable(0.0),
        Nullable(24.5),
        Nullable(0.0),
        Nullable(44.5),
        Nullable(24.5),
        Nullable(24.5),
        Nullable(""),
        Nullable(0),
        Nullable(1),
        Nullable(0),
        Nullable(0),
        Nullable(0),
        Nullable(0),
        Nullable(1),
    ]

    movies[28000] = Any[
        Nullable(28000),
        Nullable("Kiss Me Deadly"),
        Nullable(1955),
        Nullable(104),
        Nullable{Int}(),
        Nullable(7.6),
        Nullable(1836),
        Nullable(4.5),
        Nullable(4.5),
        Nullable(4.5),
        Nullable(4.5),
        Nullable(4.5),
        Nullable(4.5),
        Nullable(14.5),
        Nullable(24.5),
        Nullable(14.5),
        Nullable(24.5),
        Nullable(""),
        Nullable(0),
        Nullable(0),
        Nullable(0),
        Nullable(0),
        Nullable(0),
        Nullable(0),
        Nullable(0),
    ]

    movies[28001] = Any[
        Nullable(28001),
        Nullable("Kiss Me Goodbye"),
        Nullable(1982),
        Nullable(101),
        Nullable{Int}(),
        Nullable(5.6),
        Nullable(302),
        Nullable(4.5),
        Nullable(4.5),
        Nullable(4.5),
        Nullable(4.5),
        Nullable(14.5),
        Nullable(24.5),
        Nullable(14.5),
        Nullable(14.5),
        Nullable(4.5),
        Nullable(4.5),
        Nullable(""),
        Nullable(0),
        Nullable(0),
        Nullable(1),
        Nullable(0),
        Nullable(0),
        Nullable(0),
        Nullable(0),
    ]

    movies[28002] = Any[
        Nullable(28002),
        Nullable("Kiss Me Kate"),
        Nullable(1953),
        Nullable(109),
        Nullable{Int}(),
        Nullable(7.3),
        Nullable(729),
        Nullable(4.5),
        Nullable(4.5),
        Nullable(4.5),
        Nullable(4.5),
        Nullable(4.5),
        Nullable(14.5),
        Nullable(14.5),
        Nullable(24.5),
        Nullable(14.5),
        Nullable(24.5),
        Nullable(""),
        Nullable(0),
        Nullable(0),
        Nullable(1),
        Nullable(0),
        Nullable(0),
        Nullable(1),
        Nullable(0),
    ]

    movies[58786] = Any[
        Nullable(58786),
        Nullable("www.hellssoapopera.com"),
        Nullable(1999),
        Nullable(100),
        Nullable{Int}(),
        Nullable(6.6),
        Nullable(5),
        Nullable(24.5),
        Nullable(0),
        Nullable(24.5),
        Nullable(0),
        Nullable(0),
        Nullable(0),
        Nullable(0),
        Nullable(0),
        Nullable(24.5),
        Nullable(44.5),
        Nullable(""),
        Nullable(0),
        Nullable(0),
        Nullable(0),
        Nullable(0),
        Nullable(0),
        Nullable(0),
        Nullable(0),
    ]

    movies[58787] = Any[
        Nullable(58787),
        Nullable("xXx"),
        Nullable(2002),
        Nullable(132),
        Nullable(85000000),
        Nullable(5.5),
        Nullable(18514),
        Nullable(4.5),
        Nullable(4.5),
        Nullable(4.5),
        Nullable(4.5),
        Nullable(14.5),
        Nullable(14.5),
        Nullable(14.5),
        Nullable(14.5),
        Nullable(4.5),
        Nullable(4.5),
        Nullable("PG-13"),
        Nullable(1),
        Nullable(0),
        Nullable(0),
        Nullable(0),
        Nullable(0),
        Nullable(0),
        Nullable(0),
    ]

    movies[58788] = Any[
        Nullable(58788),
        Nullable("xXx: State of the Union"),
        Nullable(2005),
        Nullable(101),
        Nullable(87000000),
        Nullable(3.9),
        Nullable(1584),
        Nullable(24.5),
        Nullable(4.5),
        Nullable(4.5),
        Nullable(4.5),
        Nullable(4.5),
        Nullable(14.5),
        Nullable(4.5),
        Nullable(4.5),
        Nullable(4.5),
        Nullable(14.5),
        Nullable("PG-13"),
        Nullable(1),
        Nullable(0),
        Nullable(0),
        Nullable(0),
        Nullable(0),
        Nullable(0),
        Nullable(0),
    ]

    for i in [1, 2, 3, 28000, 28001, 28002, 58786, 58787, 58788]
        for j in 1:25
            if isnull(movies[i][j])
                @test isnull(M[i, j])
            else
                @test get(M[i ,j]) == get(movies[i][j])
            end
        end
    end
end
